env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11
      before_install:
        - rvm install ruby-2.5.0
      install:
        - bundle install --without=documentation
      script:
        - set -o pipefail
        - xcodebuild -scheme "Consumer" -sdk macosx clean build test | bundle exec xcpretty
      after_success: bundle exec slather
